//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opGamesLLC.opCpp2005 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("opGamesLLC.opCpp2005.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opC++ Compiler.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opC++ compiler generates standard C++ code from extended opC++ code.  For more information visit http://www.opcpp.com.
        ///Copyright 2007 opGames LLC.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAK9E2R3PRHPC1CCM2PCZHHDJPD2CQRIJRJ8ZJZDQEERAPQCDPAAPEAIH9EMACA3DRKMJIH8IDCTMIPCKCZDMKRMKRQCZRK9CCH8MMCTPZHAARRKHRQMZMEKK2ARJEAT.
        /// </summary>
        internal static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opC++ Compiler.
        /// </summary>
        internal static string _115 {
            get {
                return ResourceManager.GetString("115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Options.
        /// </summary>
        internal static string _116 {
            get {
                return ResourceManager.GetString("116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string _117 {
            get {
                return ResourceManager.GetString("117", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _1337 {
            get {
                object obj = ResourceManager.GetObject("1337", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _256 {
            get {
                object obj = ResourceManager.GetObject("256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _257 {
            get {
                object obj = ResourceManager.GetObject("257", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _258 {
            get {
                object obj = ResourceManager.GetObject("258", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _301 {
            get {
                object obj = ResourceManager.GetObject("301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _302 {
            get {
                object obj = ResourceManager.GetObject("302", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _303 {
            get {
                object obj = ResourceManager.GetObject("303", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _304 {
            get {
                object obj = ResourceManager.GetObject("304", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _305 {
            get {
                object obj = ResourceManager.GetObject("305", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _306 {
            get {
                object obj = ResourceManager.GetObject("306", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _307 {
            get {
                object obj = ResourceManager.GetObject("307", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _308 {
            get {
                object obj = ResourceManager.GetObject("308", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _309 {
            get {
                object obj = ResourceManager.GetObject("309", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
